######################## default configuration ####################
baseURL = "https://demo.gethugothemes.com/liva/examplesite/"
languageCode = "en-us"
title = "Luis Rovira's | Personal Blog"
theme = "liva-hugo"
summaryLength = "10"
paginate = 6
disqusShortname = ""

[outputs]
home = ["HTML", "RSS", "JSON"]

############################# Plugins ##############################
[params.plugins]

# CSS Plugins
[[params.plugins.css]]
URL = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
URL = "plugins/slick/slick.css"
[[params.plugins.css]]
URL = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
URL = "plugins/venobox/venobox.css"

# JS Plugins
[[params.plugins.js]]
URL = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
URL = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
URL = "plugins/slick/slick.min.js"
[[params.plugins.js]]
URL = "plugins/venobox/venobox.min.js"
[[params.plugins.js]]
URL = "plugins/search/fuse.min.js"
[[params.plugins.js]]
URL = "plugins/search/mark.js"
[[params.plugins.js]]
URL = "plugins/search/search.js"


############################## navigation ###############################
[menu]

# main menu
[[menu.main]]
name = "About"
URL = "about/"
weight = 1

[[menu.main]]
name = "Post"
URL = "blog/"
weight = 2

[[menu.main]]
name = "Contact"
URL = "contact/"
weight = 3

# footer menu
[[menu.footer]]
name = "About"
URL = "about/"
weight = 1

[[menu.footer]]
name = "Post"
URL = "blog/"
weight = 2

[[menu.footer]]
name = "Contact"
URL = "contact/"
weight = 3


#################### default parameters ################################
[params]
logo = "images/logo.png"
home = "Home"
# Meta data
description = "This is meta description"
author = "Luis Rovira"
# Google Analitycs
googleAnalitycsID = "Your ID"
# Contact Information
mobile = "+573052419359"
email = "lercoagencia@gmail.com"
location = "Medellin, Colombia"
# copyright
copyright = "| copyright &copy; 2024 Luis Rovira All Rights Reserved |"

# Preloader
[params.preloader]
enable = true
preloader = "" # use .png , .svg or .gif format

# search
[params.search]
enable = true

############################ news letter ########################
[params.newsletter]
enable = true
title = "Join Our Newsletter"
content = "Stay in the loop with the latest trends, insights, and updates in React development and UI/UX design by subscribing to our newsletter! Join our community of passionate developers, designers, and tech enthusiasts who receive exclusive content, helpful tips, and exciting news directly to their inbox."


# cookies
[params.cookies]
enable = true
expire_days = 2


############################# social site ########################

[[params.social]]
title = "instagram"
icon = "ti-instagram" # themify icon : https://themify.me/themify-icons
link = "https://www.instagram.com/luiserovira/"

[[params.social]]
title = "github"
icon = "ti-github" # themify icon : https://themify.me/themify-icons
link = "https://github.com/luisroviraco"

[[params.social]]
title = "linkedin"
icon = "ti-linkedin" # themify icon : https://themify.me/themify-icons
link = "https://www.linkedin.com/in/luis-rovira-776887140/"
